### ISSUE TITLE
To install

### ISSUE THREAD

**Issue by sy-project** [gbmhunter/CppLinuxSerial#10]
i download this, use git clone.

and i complete for mkdir build && cd build.

but i have error for cmake ..

build message is

-- The C compiler identification is GNU 9.3.0
-- The CXX compiler identification is GNU 9.3.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
BUILD_TESTS=TRUE, unit tests will be built.
CMake Error at /usr/share/cmake-3.16/Modules/ExternalProject.cmake:2421 (message):
  error: could not find git for clone of googletest
Call Stack (most recent call first):
  /usr/share/cmake-3.16/Modules/ExternalProject.cmake:3236 (_ep_add_download_command)
  CMakeLists.txt:6 (ExternalProject_Add)

-- Configuring incomplete, errors occurred!
See also "/home/resfact/Downloads/CppLinuxSerial-master/build/googletest-download/CMakeFiles/CMakeOutput.log".
CMake Error at CMakeLists.txt:26 (message):
  CMake step for googletest failed: 1

-- Configuring incomplete, errors occurred!
See also "/home/resfact/Downloads/CppLinuxSerial-master/build/CMakeFiles/CMakeOutput.log".

what should i do?

my os is ubuntu 20.04

**Comment by doleron** [comment]
Hi! Are you sure you have git installed? You can check it by opening a terminal and typing:

```
git --version
```

If ubuntu reply with something like:

```
git: command not found
```
You probably don't have git installed yet. To install git just type:

```
sudo apt install git
```

**Comment by sy-project** [comment]
thanks i reinstall git, and solved this problem

**Comment by doleron** [comment]
You are welcome. Glad to know you managed to fix it.
