### ISSUE TITLE
Support for "disable auto reset on connect"

### ISSUE THREAD

**Issue by doleron** [gbmhunter/CppLinuxSerial#11]
Hi!

I'm trying to provide support to **DisablingAutoResetOnSerialConnection** as discussed [here](https://playground.arduino.cc/Main/DisablingAutoResetOnSerialConnection/).

By I can understand, on Linux it can be achieved by controlling the bit HUPCL as described [here](https://man7.org/linux/man-pages/man3/termios.3.html):

**HUPCL**  _Lower modem control lines after last process closes the device (hang up)._

Thus, I added:

```c++
void SerialPort::SetResetOnDisconnect(bool val)
{
    hang_up_on_disconection_ = val;
    if(state_ == State::OPEN)
        ConfigureTermios();
}
```
and

```c++
void SerialPort::ConfigureTermios()
{
     //... 
    if (hang_up_on_disconection_)
    {
        tty.c_cflag &= HUPCL;
    } else 
    {
        tty.c_cflag &= ~HUPCL;
     }

}
```

But it is not working =( I'm not sure the problem is with my current settings (Ubuntu on Virtualbox accessing arduino via USB virtualbox passthrough) or if there are something else to do in the code.

Any ideas?

**Comment by gbmhunter** [comment]
Hi @doleron , even though you closed it, I'm interested in what solution you arrived to, and if it's worth integrating into this library.
