### ISSUE TITLE
Can I use this header for usb relay board?

### ISSUE THREAD

**Issue by sy-project** [gbmhunter/CppLinuxSerial#12]
can i use this for 32channel usb relay board?

my relay board is [this](http://vctec.co.kr/product/32%EC%B1%84%EB%84%90-usb-%EB%A6%B4%EB%A0%88%EC%9D%B4-%EB%AA%A8%EB%93%88-32-channel-usb-relay-module/5262/)

**Comment by doleron** [comment]
I haven't used this particular board yet but by what I can read on [this doc](https://numato.com/kb/understanding-readallwriteall-commands-for-relay-modules/) it seems that you can use the [basic CppLinuxSerial example](https://github.com/gbmhunter/CppLinuxSerial#examples) to send commands like:

```c++
SerialPort serialPort(/*initialize the serial port*/);

serialPort.Write("relay readall");
std::string response;
serialPort.Read(response);
```
Thus, the string `response` would be something like `0000000F`

**Comment by gbmhunter** [comment]
Hi @sy-project without spending a large amount of time going into the specifics, you should be able to read back serial port data using this library. Bear in mind that if the relays return binary bitfield data you will have to convert the returned `std::string` into the appropriate data type, printing it directly in that case will not give you `000.....F`.
