### ISSUE TITLE
i cant open serial port

### ISSUE THREAD

**Issue by sy-project** [gbmhunter/CppLinuxSerial#13]
my code is 

#include <CppLinuxSerial/SerialPort.hpp>

using namespace mn::CppLinuxSerial;

int main() {
	// Create serial port object and open serial port
	SerialPort serialPort("/dev/ttyACM1", 19200);
	// Use SerialPort serialPort("/dev/ttyACM0", 13000); instead if you want to provide a custom baud rate
	printf("A");
	serialPort.SetTimeout(-1); // Block when reading until any data is received
	printf("A");
	serialPort.Open();
	printf("A");

	// Write some ASCII datae
	serialPort.Write("relay writeall ffffffff");
	printf("A");

	// Read some data back (will block until at least 1 byte is received due to the SetTimeout(-1) call above)
	std::string readData;
	printf("A");
	serialPort.Read(readData);
	printf("A");

	// Close the serial port
	serialPort.Close();
}

but my scene doesnt print "A". what should i do?

![Screenshot from 2021-03-15 10-58-15](https://user-images.githubusercontent.com/42532250/111093988-9741a500-857d-11eb-99ec-a91cfae264a3.png)

**Comment by patcmorneau** [comment]
user is in dialout group?

**Comment by gbmhunter** [comment]
Hmmm, so it may not even be making it past `SerialPort serialPort("/dev/ttyACM1", 19200);` (unless it is but not flushing the stdout buffer). One thing to try would be to add a `printf()` statement before the first line of code involving the serial port, and see if at least you get 1 "A" then.

**Comment by patcmorneau** [comment]
other debugging solution :
if you are able to cat the device with sudo but not without sudo, its a permission issue
