### ISSUE TITLE
Send HEX commands over Serial

### ISSUE THREAD

**Issue by thhilt** [gbmhunter/CppLinuxSerial#15]
Hi, 

First, thanks for this great library!

I need to send HEX commands over serial, and AFAIK it is possible to send only String commands over serial.
Would it be possible to add this feature to the library? Or do I have to use some trick to complete it?

Many thanks!

**Comment by gbmhunter** [comment]
Hi @thhilt you should be able to! The std::string can be treated like a std::vector<char>, you should be able to send any form of data (strings, hex encoded, raw binary, e.t.c) using it (std::strings can also contain null). It does make me wonder however if I should add an overloaded method that accepts a std::vector<char> to make it clearer to the user....

**Comment by thhilt** [comment]
Thanks @gbmhunter for your answer! 

So I should be able to send a command like this one `serialPort.Write("\x01\x06\x20\x0e\x00\x08\xe2\x0f");`, is that right? Because I can't see any reaction of my serial device. Or maybe I'm missing something...

**Comment by gbmhunter** [comment]
@thhilt yes that's correct, it should work. I'll try and get around to testing your use case sometime in the next day or two to make sure this works as expected.

**Comment by thhilt** [comment]
@gbmhunter I tested again, and I'm still unable to communicate with my serial device. Did you had some time to test it with hex commands from your side?

**Comment by gbmhunter** [comment]
Hi @thhilt , I tried some basic commands on a Linux virtual machine, but I was getting weird behaviour when trying to "pass through" the USB-to-serial device into the VM so wasn't able to really test much sorry!

**Comment by thhilt** [comment]
@gbmhunter got it, but thanks anyway for that and your time to help me!

While testing again and again, I found some interesting topic about how to write an HEX string: https://stackoverflow.com/a/49273626/13329066 

So I wrote this:

```cpp
SerialPort serialPort("/dev/ttyUSB0", BaudRate::B_115200);
serialPort.SetTimeout(100); // Block when reading until any data is received
serialPort.SetEcho(true);
serialPort.Open();

// Debug
cout << "Serial port /dev/ttyUSB0 opened successfully" << endl;         

// Generating message
 std::string hex = "0106200E0008E20F";

std::basic_string<uint8_t> bytes;

for (size_t i = 0; i < hex.length(); i += 2)
  {
      uint16_t byte;

      std::string nextbyte = hex.substr(i, 2);

      std::istringstream(nextbyte) >> std::hex >> byte;

      bytes.push_back(static_cast<uint8_t>(byte));
}

std::string result(begin(bytes), end(bytes));

// Write 
serialPort.Write(result);

// Read some data back (will block until at least 1 byte is received due to the SetTimeout(-1) call above)
std::string readData;
serialPort.Read(readData);

cout << "data read: " << readData << endl;

// Close the serial port
serialPort.Close();
```

And it works! I don't know if it's the best way to generate an HEX message in C++, but at least it works for now...
