### ISSUE TITLE
Install Problem

### ISSUE THREAD

**Issue by ABeginnerThomas** [gbmhunter/CppLinuxSerial#19]
Hi,
my english is not so good sorry.

I make this Command during installation: "cmake .."
Then I become this errormessage:

------------------------------------------
BUILD_TESTS=TRUE, unit tests will be built.
CMake Deprecation Warning at CMakeLists.txt:1 (cmake_minimum_required):
  Compatibility with CMake < 2.8.12 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.

-- Configuring done
-- Generating done
-- Build files have been written to: /home/tg/C/CppLinuxSerial/build/googletest-download
[ 11%] Performing download step (git clone) for 'googletest'
Error removing directory "/home/tg/C/CppLinuxSerial/build/googletest-src".
CMake Error at googletest-download/googletest-prefix/tmp/googletest-gitclone.cmake:12 (message):
  Failed to remove directory:
  '/home/tg/C/CppLinuxSerial/build/googletest-src'

make[2]: *** [CMakeFiles/googletest.dir/build.make:99: googletest-prefix/src/googletest-stamp/googletest-download] Fehler 1
make[1]: *** [CMakeFiles/Makefile2:83: CMakeFiles/googletest.dir/all] Fehler 2
make: *** [Makefile:91: all] Fehler 2
CMake Error at CMakeLists.txt:33 (message):
  Build step for googletest failed: 2

-- Configuring incomplete, errors occurred!
See also "/home/tg/C/CppLinuxSerial/build/CMakeFiles/CMakeOutput.log".
[tg@thomas-virtualbox build]$ ^C
[tg@thomas-virtualbox build]$ cmake ..
BUILD_TESTS=TRUE, unit tests will be built.
CMake Deprecation Warning at CMakeLists.txt:1 (cmake_minimum_required):
  Compatibility with CMake < 2.8.12 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.

-- Configuring done
-- Generating done
-- Build files have been written to: /home/tg/C/CppLinuxSerial/build/googletest-download
[ 11%] Performing download step (git clone) for 'googletest'
Error removing directory "/home/tg/C/CppLinuxSerial/build/googletest-src".
CMake Error at googletest-download/googletest-prefix/tmp/googletest-gitclone.cmake:12 (message):
  Failed to remove directory:
  '/home/tg/C/CppLinuxSerial/build/googletest-src'

make[2]: *** [CMakeFiles/googletest.dir/build.make:99: googletest-prefix/src/googletest-stamp/googletest-download] Fehler 1
make[1]: *** [CMakeFiles/Makefile2:83: CMakeFiles/googletest.dir/all] Fehler 2
make: *** [Makefile:91: all] Fehler 2
CMake Error at CMakeLists.txt:33 (message):
  Build step for googletest failed: 2

-- Configuring incomplete, errors occurred!
------------------------------------------------------

Can you please help me? I am an Linux and c Beginner :-(

**Comment by LRDPRDX** [comment]
It seems you're using old version of CMake (2). Try to update to the newer one (3).

**Comment by gbmhunter** [comment]
Thanks @LRDPRDX, @ABeginnerThomas report back if that fixed the problem. Also note there is an issue with the googletest branch requesting `master` but it needs to be `main`, this has been fixed as of https://github.com/gbmhunter/CppLinuxSerial/commit/819155b9510b981b2f9b0087f6b8c2e9bac65060
