### ISSUE TITLE
state == OPEN when trying to set the timeout before the open call

### ISSUE THREAD

**Issue by CodeFatherG** [gbmhunter/CppLinuxSerial#2]
Hi,

I am using this library on the raspberry pi to communicate with an arduino uno. I am experiencing an error in that when setting the timeout to -1 I receive an error that the state==open even before I call the open function. I tried surrounding this in a try catch and closing if this was caught but the close call fails as well. Do you have suggestions or perhaps know of any meta packages I should check are installed on my pi? 

Thanks, Grant.

**Comment by gbmhunter** [comment]
Hi Grant! Thanks for trying out the library. What is the exact error you are getting? And when exactly does it occur? (you mentioned the error occurs "before I call the open function", what function is being run when you get the error?). Hopefully with some more info I can look into it (I don't have a RPi handy on me at the moment though).

**Comment by CodeFatherG** [comment]
Hi @gbmhunter ,

For my application, I have to set the timeout to -1, here is the init code:
```c++
void init_serial(mn::CppLinuxSerial::SerialPort *serial_port){
    serial_port->SetTimeout(-1);
    serial_port->Open();
}
```

The error I receive is:
```c++
void mn::CppLinuxSerial::SerialPort::SetTimeout (int32_t) called while state == OPEN
```

**Comment by gbmhunter** [comment]
@ThePapaG thanks for the information.

I had a poke around the code and noticed that the state was not being set to `CLOSED` in the constructor. In all my unit tests the state defaults to `CLOSED`, but perhaps this is undefined behaviour. I have explicitly set the state to `CLOSED` in the constructor on the `develop` branch, could you pull that and give the code a test?

**Comment by gbmhunter** [comment]
Closing as no reply. Bug mentioned above is fixed in https://github.com/gbmhunter/CppLinuxSerial/pull/4, state is now explicitly set to `CLOSED` upon construction.
