### ISSUE TITLE
stop bit and Parity

### ISSUE THREAD

**Issue by RamatovInomjon** [gbmhunter/CppLinuxSerial#20]
Hi @gbmhunter Thanks for your work!
How can I set the parity EVEN, stop bit 1, Databits 7

**Comment by gbmhunter** [comment]
Hi @RamatovInomjon , it's something I haven't yet added support for, but I should do! Will try and add support for setting the parity, num. stop bits and num. databits in the next few days.

**Comment by gbmhunter** [comment]
Done! Sorry I did this a while ago, but forgot to close the issue!
