### ISSUE TITLE
Read data from Arduino is wrong

### ISSUE THREAD

**Issue by Chao-Shun-Cheng** [gbmhunter/CppLinuxSerial#29]
I try to use this library to communicate with arduino.
Now, I try the example code to test. However, I always receive the wrong message.

![Screenshot from 2022-07-11 18-51-20](https://user-images.githubusercontent.com/48173999/178248768-1779f533-ded0-4553-91b2-0b1c5f6c8b9f.png)

Thank you in advance.

**Comment by Mark-Wills** [comment]
HI,

This looks normal to me - it's not an issue with the serial library. Try adding a delay in your Arduino code after you send the string.

Serial.Write("Hello");
delay(150);

That will probably sort it.

**Comment by Chao-Shun-Cheng** [comment]
Thank you.
I have solved this issue by adding a delay.
