### ISSUE TITLE
read timeout and eof are indistinguishable

### ISSUE THREAD

**Issue by aldoshkind** [gbmhunter/CppLinuxSerial#32]
Hello!
I am trying to write program which is able to detect device disconnection. I use usb serial device. My platform is Ubuntu 18.04 x86.
According to documentation `read` returns 0 on `eof`, and same happens if timeout occurs. I need both timeout and disconnection detection in my project.
The only correct solution I found is to use `int rv = ioctl(fd, TCGETS2, &term2);` if read returns 0. If `rv` equals -1 and `errno` equals 5 (`EIO`) - device has been disconnected, timeout happened otherwise. Key problem here is that EIO is not documented in local mans, neither in the mans I see on the Internet (except few mans which I am not sure are related to Linux and up-to-date).
Please dig this problem and find correct solution!
Thanks!

**Comment by gbmhunter** [comment]
Hi @aldoshkind . I don't have the time to dig into this myself, but welcome a pull request to improve this library if you manage to improve the code to detect these different error conditions!

**Comment by gbmhunter** [comment]
Fixed in 085f5468475af3654a1b99685790f8cbff6919af (thanks for the PR @aldoshkind !).
